/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as FoundersNoteRouteImport } from './routes/founders-note'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as ApiPushConfigRouteImport } from './routes/api/push/config'
import { Route as ApiPushSendRouteImport } from './routes/api/push/send'
import { Route as ApiPushSubscribeRouteImport } from './routes/api/push/subscribe'
import { Route as ApiStripeCheckoutRouteImport } from './routes/api/stripe/checkout'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundersNoteRoute = FoundersNoteRouteImport.update({
  id: '/founders-note',
  path: '/founders-note',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const ApiPushConfigRoute = ApiPushConfigRouteImport.update({
  id: '/api/push/config',
  path: '/api/push/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushSendRoute = ApiPushSendRouteImport.update({
  id: '/api/push/send',
  path: '/api/push/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushSubscribeRoute = ApiPushSubscribeRouteImport.update({
  id: '/api/push/subscribe',
  path: '/api/push/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeCheckoutRoute = ApiStripeCheckoutRouteImport.update({
  id: '/api/stripe/checkout',
  path: '/api/stripe/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/founders-note': typeof FoundersNoteRoute
  '/offers': typeof OffersRoute
  '/blog/': typeof BlogIndexRoute
  '/api/push/config': typeof ApiPushConfigRoute
  '/api/push/send': typeof ApiPushSendRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/founders-note': typeof FoundersNoteRoute
  '/offers': typeof OffersRoute
  '/blog': typeof BlogIndexRoute
  '/api/push/config': typeof ApiPushConfigRoute
  '/api/push/send': typeof ApiPushSendRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/founders-note': typeof FoundersNoteRoute
  '/offers': typeof OffersRoute
  '/blog/': typeof BlogIndexRoute
  '/api/push/config': typeof ApiPushConfigRoute
  '/api/push/send': typeof ApiPushSendRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/founders-note'
    | '/offers'
    | '/blog/'
    | '/api/push/config'
    | '/api/push/send'
    | '/api/push/subscribe'
    | '/api/stripe/checkout'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/founders-note'
    | '/offers'
    | '/blog'
    | '/api/push/config'
    | '/api/push/send'
    | '/api/push/subscribe'
    | '/api/stripe/checkout'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/founders-note'
    | '/offers'
    | '/blog/'
    | '/api/push/config'
    | '/api/push/send'
    | '/api/push/subscribe'
    | '/api/stripe/checkout'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  FoundersNoteRoute: typeof FoundersNoteRoute
  OffersRoute: typeof OffersRoute
  ApiPushConfigRoute: typeof ApiPushConfigRoute
  ApiPushSendRoute: typeof ApiPushSendRoute
  ApiPushSubscribeRoute: typeof ApiPushSubscribeRoute
  ApiStripeCheckoutRoute: typeof ApiStripeCheckoutRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founders-note': {
      id: '/founders-note'
      path: '/founders-note'
      fullPath: '/founders-note'
      preLoaderRoute: typeof FoundersNoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/push/config': {
      id: '/api/push/config'
      path: '/api/push/config'
      fullPath: '/api/push/config'
      preLoaderRoute: typeof ApiPushConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/send': {
      id: '/api/push/send'
      path: '/api/push/send'
      fullPath: '/api/push/send'
      preLoaderRoute: typeof ApiPushSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/subscribe': {
      id: '/api/push/subscribe'
      path: '/api/push/subscribe'
      fullPath: '/api/push/subscribe'
      preLoaderRoute: typeof ApiPushSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/checkout': {
      id: '/api/stripe/checkout'
      path: '/api/stripe/checkout'
      fullPath: '/api/stripe/checkout'
      preLoaderRoute: typeof ApiStripeCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  FoundersNoteRoute: FoundersNoteRoute,
  OffersRoute: OffersRoute,
  ApiPushConfigRoute: ApiPushConfigRoute,
  ApiPushSendRoute: ApiPushSendRoute,
  ApiPushSubscribeRoute: ApiPushSubscribeRoute,
  ApiStripeCheckoutRoute: ApiStripeCheckoutRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
